// Copyright: 2024 Robert Peter Meyer
// License: MIT
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
using System.Diagnostics.CodeAnalysis;

using BB84.EntityFrameworkCore.Entities.Abstractions.Components;
using BB84.EntityFrameworkCore.Repositories.SqlServer.Extensions;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BB84.EntityFrameworkCore.Repositories.SqlServer.Configurations;

/// <summary>
/// Provides the SQL Server specific property configuration used by the entity type configuration
/// base classes of this package.
/// </summary>
/// <remarks>
/// The provider-agnostic counterpart lives in the <c>BB84.EntityFrameworkCore.Repositories</c>
/// package. Only defaults that cannot be expressed without SQL Server belong here.
/// </remarks>
[SuppressMessage("Style", "IDE0058", Justification = "Not relevant here, entity type configuration.")]
internal static class EntityTypeBuilderDefaults
{
	/// <summary>
	/// Configures whether the primary key of the entity is clustered.
	/// </summary>
	/// <typeparam name="TEntity">The type of the entity being configured.</typeparam>
	/// <typeparam name="TKey">The type of the primary key for the entity.</typeparam>
	/// <param name="builder">The builder for the entity type being configured.</param>
	/// <param name="clustered">Whether the primary key is clustered.</param>
	internal static void ApplyKeyClustering<TEntity, TKey>(EntityTypeBuilder<TEntity> builder, bool clustered)
		where TEntity : class, IIdentity<TKey>
		where TKey : IEquatable<TKey>
	{
		builder.HasKey(e => e.Id)
			.IsClustered(clustered);
	}

	/// <summary>
	/// Configures the creator and editor columns of the entity as <b>sysname</b> columns.
	/// </summary>
	/// <remarks>
	/// Only applies to entities that use the default <see cref="string"/> based creator and editor.
	/// </remarks>
	/// <typeparam name="TEntity">The type of the entity being configured.</typeparam>
	/// <param name="builder">The builder for the entity type being configured.</param>
	internal static void ApplySysNameAuditColumns<TEntity>(EntityTypeBuilder<TEntity> builder)
		where TEntity : class, IUserAudited<string, string?>
	{
		builder.Property(e => e.CreatedBy)
			.IsSysNameColumn();

		builder.Property(e => e.EditedBy)
			.IsSysNameColumn();
	}

	/// <summary>
	/// Configures the identifier column of the entity to be generated by the database.
	/// </summary>
	/// <remarks>
	/// Only applies to entities that use the default <see cref="Guid"/> based primary key.
	/// </remarks>
	/// <typeparam name="TEntity">The type of the entity being configured.</typeparam>
	/// <param name="builder">The builder for the entity type being configured.</param>
	internal static void ApplyGuidIdDefault<TEntity>(EntityTypeBuilder<TEntity> builder)
		where TEntity : class, IIdentity<Guid>
	{
		builder.Property(e => e.Id)
			.HasDefaultValueSql("NEWID()");
	}
}
